name: Lint, Build, and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint with flake8
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
          # si tu as un requirements.txt dans python/
          if [ -f python/requirements.txt ]; then pip install -r python/requirements.txt; fi

      - name: Run flake8
        run: flake8 python/ --max-line-length=120

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: lint
    services:
      docker:
        image: docker:latest
        options: --privileged
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker images
        run: docker compose build

  test:
    name: Run Python tests with pytest
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f python/requirements.txt ]; then pip install -r python/requirements.txt; fi

      - name: Run tests
        run: pytest -q
